services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s       # Check every 10 seconds
      retries: 5          # Try 5 times before marking it unhealthy
      start_period: 30s   # Wait 30 seconds before starting health checks
      timeout: 5s         # Consider it failed if no response within 5 seconds
  
  spring-boot-app:
    image: accessing-data-mysql:0.0.1-SNAPSHOT
    depends_on:
      mysql:
        condition: service_healthy   # Wait until MySQL is healthy before starting
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
